http:
  host: "localhost"
  port: 3030
  auth_key: ""
grpc:
  host: "localhost"
  port: 3040
sentry:
  dsn: ""
storage:
  name: "mysql"
  dsn: "root:pass@tcp(127.0.0.1:3306)/dbname?parseTime=true"
senders:
  - name: "" # ex. smtp
    host: ""
    port:
    tls: # ex. true|false
    username: ""
    password: ""
    interval: "" # ex. 10s
    pause: "" # ex. 1s
    limit: "" # ex. 10
    status: "" # ex. created|error|sent
    default: # ex. true|false