pkgname="mysql"
output="./boiler/models/mysql"

[mysql]
  dbname="exapmle_db"
  host="localhost"
  port=3306
  user="root"
  pass=""
  sslmode="false"
  blacklist=["mig_migrations"]
  whitelist=["email"]
