http:
  host: "{{http.host}}"
  port: {{http.port}}
  auth_key: "{{http.auth_key}}"
mysql:
  dsn: "{{mysql.dsn}}"
smtp:
  host: "{{smtp.host}}"
  port: {{smtp.port}}
  user: "{{smtp.user}}"
  password: "{{smtp.password}}"